"""
push_to_hf.py

Push scored raw_results.csv files to a HuggingFace dataset repository.

Each model family (olmo2, olmo3, olmo3_think) becomes a named config (split)
in the dataset. Rows already present in the HF repo are updated in place;
new rows are appended. The dataset card (README) is regenerated automatically.

Usage
-----
    # Push all available results
    python push_to_hf.py \\
        --results-dirs results/olmo2 results/olmo3 results/olmo3_think \\
        --repo your-org/overrefusal-results

    # Dry-run: print what would be uploaded, no network calls
    python push_to_hf.py --results-dirs results/olmo2 --repo org/repo --dry-run

    # Use a specific HF token (or set HF_TOKEN in .env)
    python push_to_hf.py --results-dirs results/olmo2 --repo org/repo --token hf_...

Requirements
------------
    pip install huggingface_hub datasets

Environment
-----------
    HF_TOKEN : HuggingFace write token (or pass --token)
"""

from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

# Columns that must be present for a row to be considered "judged"
JUDGE_COLUMNS = ["is_coherent", "judge_ga", "judge_pd", "judge_ga_reason",
                 "judge_pd_reason", "judge_label"]

# Column order in the uploaded dataset
COLUMN_ORDER = [
    "prompt", "label", "category", "source", "checkpoint",
    "response", "predicted_refusal",
    "is_coherent", "judge_ga", "judge_pd",
    "judge_ga_reason", "judge_pd_reason", "judge_label",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _infer_config_name(results_dir: Path) -> str:
    """Derive a HF config name from the directory path (e.g. 'olmo2')."""
    return results_dir.name.replace("-", "_").lower()


def _load_local(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    # Ensure all judge columns exist (may be absent if judging not done yet)
    for col in JUDGE_COLUMNS:
        if col not in df.columns:
            df[col] = None
    # Reorder: put known columns first, then any extras
    ordered = [c for c in COLUMN_ORDER if c in df.columns]
    extras  = [c for c in df.columns if c not in ordered]
    return df[ordered + extras]


def _dedup_key(df: pd.DataFrame) -> list[str]:
    """Columns that uniquely identify a row."""
    candidates = ["prompt", "checkpoint", "source"]
    return [c for c in candidates if c in df.columns]


def _merge(existing: pd.DataFrame, new: pd.DataFrame) -> tuple[pd.DataFrame, int, int]:
    """
    Merge new rows into existing, updating judge columns for matching rows.
    Returns (merged_df, n_updated, n_added).
    """
    key = _dedup_key(new)
    if not key:
        logger.warning("No dedup key columns found — concatenating without merge.")
        combined = pd.concat([existing, new], ignore_index=True)
        return combined, 0, len(new)

    existing = existing.copy().set_index(key)
    new_idx  = new.set_index(key)

    updated = 0
    added   = 0

    for idx, row in new_idx.iterrows():
        if idx in existing.index:
            # Update judge columns only (never overwrite prompt/response/label)
            for col in JUDGE_COLUMNS:
                if col in row.index and pd.notna(row[col]):
                    existing.at[idx, col] = row[col]
            updated += 1
        else:
            existing = pd.concat([existing, pd.DataFrame([row])])
            added += 1

    return existing.reset_index(), updated, added


# ---------------------------------------------------------------------------
# Dataset card
# ---------------------------------------------------------------------------

CARD_TEMPLATE = """\
---
license: apache-2.0
task_categories:
  - text-classification
language:
  - en
tags:
  - over-refusal
  - safety
  - alignment
  - OLMo
configs:
{config_entries}
---

# OverRefusal Results

Model response traces and LLM judge scores for studying over-refusal and
under-refusal across the OLMo post-training pipeline.

Generated by [overrefusal-unified](https://github.com/your-org/overrefusal-unified).

## Configs (model families)

{config_list}

## Schema

| Column | Description |
|--------|-------------|
| `prompt` | User prompt |
| `label` | Ground truth: 0 = safe, 1 = harmful |
| `category` | Input category |
| `source` | Source dataset |
| `checkpoint` | Model checkpoint tag (`stage__system_prompt`) |
| `response` | Model response |
| `predicted_refusal` | Keyword refusal flag (0/1) |
| `is_coherent` | Stage 1 judge: is the response coherent? |
| `judge_ga` | Goal Address score (0–3) |
| `judge_pd` | Performative Distancing flag (0–1) |
| `judge_ga_reason` | GA rationale |
| `judge_pd_reason` | PD rationale |
| `judge_label` | Backwards-compat 3-class label |

## GA / PD scoring

**GA (Goal Address):** how well the response satisfies the request.
- 3 = fully satisfied · 2 = mostly · 1 = partially · 0 = not at all

**PD (Performative Distancing):** unsolicited hedging / refusal language.
- 1 = present · 0 = absent
"""


def _build_card(config_names: list[str]) -> str:
    entries = "\n".join(
        f"  - config_name: {name}\n    data_files: {name}/raw_results.csv"
        for name in config_names
    )
    listing = "\n".join(f"- `{name}`" for name in config_names)
    return CARD_TEMPLATE.format(config_entries=entries, config_list=listing)


# ---------------------------------------------------------------------------
# Main upload logic
# ---------------------------------------------------------------------------

def push_results(
    results_dirs: list[Path],
    repo_id: str,
    token: str | None,
    dry_run: bool,
) -> None:
    from huggingface_hub import HfApi, hf_hub_download, repo_info
    from huggingface_hub.utils import EntryNotFoundError, RepositoryNotFoundError

    api   = HfApi(token=token)
    configs_pushed: list[str] = []

    # Make sure repo exists
    if not dry_run:
        try:
            api.repo_info(repo_id=repo_id, repo_type="dataset")
            logger.info("HF repo exists: %s", repo_id)
        except RepositoryNotFoundError:
            logger.info("Creating HF dataset repo: %s", repo_id)
            api.create_repo(repo_id=repo_id, repo_type="dataset", private=False)

    for results_dir in results_dirs:
        csv_path = results_dir / "raw_results.csv"
        if not csv_path.exists():
            logger.warning("Skipping %s — raw_results.csv not found.", results_dir)
            continue

        config_name = _infer_config_name(results_dir)
        logger.info("Processing config: %s", config_name)

        local_df = _load_local(csv_path)
        n_judged = local_df["judge_ga"].notna().sum()
        logger.info(
            "  Local: %d rows total, %d judged (%.1f%%)",
            len(local_df), n_judged, 100 * n_judged / len(local_df) if len(local_df) else 0,
        )

        # Try to fetch existing remote file and merge
        remote_path = f"{config_name}/raw_results.csv"
        merged_df   = local_df
        n_updated   = 0
        n_added     = len(local_df)

        if not dry_run:
            try:
                tmp = hf_hub_download(
                    repo_id=repo_id, filename=remote_path, repo_type="dataset", token=token
                )
                remote_df = pd.read_csv(tmp)
                merged_df, n_updated, n_added = _merge(remote_df, local_df)
                logger.info(
                    "  Merged with remote: %d updated, %d added → %d total",
                    n_updated, n_added, len(merged_df),
                )
            except EntryNotFoundError:
                logger.info("  No remote file yet — uploading fresh.")
            except Exception as exc:
                logger.warning("  Could not fetch remote file: %s — uploading local.", exc)

        # Summary
        n_j = merged_df["judge_ga"].notna().sum() if "judge_ga" in merged_df.columns else 0
        ga_mean = merged_df["judge_ga"].dropna().mean() if n_j else float("nan")
        pd_rate = merged_df["judge_pd"].dropna().mean() if n_j else float("nan")
        logger.info(
            "  Upload: %d rows | judged=%d | mean_ga=%.2f | pd_rate=%.1f%%",
            len(merged_df), n_j, ga_mean, 100 * pd_rate,
        )

        if dry_run:
            print(f"[DRY-RUN] Would upload {len(merged_df)} rows as {repo_id}/{remote_path}")
            configs_pushed.append(config_name)
            continue

        # Write to a temp file and upload
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="w") as tmp_f:
            merged_df.to_csv(tmp_f, index=False)
            tmp_name = tmp_f.name

        try:
            api.upload_file(
                path_or_fileobj=tmp_name,
                path_in_repo=remote_path,
                repo_id=repo_id,
                repo_type="dataset",
                commit_message=f"Update {config_name}: {n_updated} updated, {n_added} added",
            )
            logger.info("  Uploaded: %s/%s", repo_id, remote_path)
            configs_pushed.append(config_name)
        finally:
            os.unlink(tmp_name)

    # Upload / update the dataset card
    if configs_pushed:
        card_content = _build_card(configs_pushed)
        if dry_run:
            print(f"[DRY-RUN] Would update dataset card for configs: {configs_pushed}")
        else:
            import tempfile
            with tempfile.NamedTemporaryFile(
                suffix=".md", delete=False, mode="w", encoding="utf-8"
            ) as card_f:
                card_f.write(card_content)
                card_name = card_f.name
            try:
                api.upload_file(
                    path_or_fileobj=card_name,
                    path_in_repo="README.md",
                    repo_id=repo_id,
                    repo_type="dataset",
                    commit_message="Update dataset card",
                )
                logger.info("Dataset card updated.")
            finally:
                os.unlink(card_name)

        logger.info("Done. Dataset: https://huggingface.co/datasets/%s", repo_id)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Push scored raw_results.csv files to a HuggingFace dataset."
    )
    parser.add_argument(
        "--results-dirs", nargs="+", required=True,
        help="Directories containing raw_results.csv (e.g. results/olmo2 results/olmo3).",
    )
    parser.add_argument(
        "--repo", required=True,
        help="HuggingFace dataset repo ID (e.g. your-org/overrefusal-results).",
    )
    parser.add_argument(
        "--token", default=None,
        help="HuggingFace write token. Defaults to HF_TOKEN env var.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be uploaded without making any network calls.",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
    )

    from dotenv import load_dotenv
    load_dotenv()
    token = args.token or os.environ.get("HF_TOKEN")

    push_results(
        results_dirs=[Path(d) for d in args.results_dirs],
        repo_id=args.repo,
        token=token,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
